### ISSUE TITLE
PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue

### ISSUE THREAD

**Issue by alb-i986** [witspirit/IntelliJBehave#28]
Hi

I installed your nice plugin, but I get the following exception (it is repeatedly thrown every X minutes):

```
com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:173)
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
    at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinitions(StepPsiReference.java:109)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinition(StepPsiReference.java:102)
    at com.github.kumaraman21.intellijbehave.codeInspector.UndefinedStepInspection$1.visitElement(UndefinedStepInspection.java:62)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:289)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:258)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:255)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:278)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

Also, navigating to the step method by hitting CTRL+B in a story is not working. I guess it is related to the exception.

Thanks in advance for any hint.

**Comment by evgeniy-khatko** [comment]
Same for me:
4:30:08 PM ClassCastException: com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue

Happens every time I open .story file or click on a step.
Stacktrace
=========
com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl cannot be cast to com.intellij.psi.PsiArrayInitializerMemberValue
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:173)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
	at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.multiResolve(StepPsiReference.java:119)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:56)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:315)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:88)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by mrge-org** [comment]
Is there any way to avoid this class cast exception? After I did fresh install of the PC it started to appear.

**Comment by mrge-org** [comment]
I created a pull request for fixing this issue. Can someone test it?
https://github.com/witspirit/IntelliJBehave/pull/36
