### ISSUE TITLE
NPE in IDEA 2016.2 on application open

### ISSUE THREAD

**Issue by longtimeago** [witspirit/IntelliJBehave#40]
Good day!
Could you, please, take a look at this exception?

``` java
null
java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
    at java.util.regex.Matcher.reset(Matcher.java:309)
    at java.util.regex.Matcher.<init>(Matcher.java:229)
    at java.util.regex.Pattern.matcher(Pattern.java:1093)
    at org.jbehave.core.steps.PatternVariantBuilder.variantsFor(PatternVariantBuilder.java:140)
    at org.jbehave.core.steps.PatternVariantBuilder.<init>(PatternVariantBuilder.java:117)
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:58)
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:55)
    at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:318)
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
    at com.google.common.collect.FluentIterable.toSet(FluentIterable.java:396)
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:181)
    at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
    at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
    at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinitions(StepPsiReference.java:109)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinition(StepPsiReference.java:102)
    at com.github.kumaraman21.intellijbehave.codeInspector.UndefinedStepInspection$1.visitElement(UndefinedStepInspection.java:62)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by JenoDK** [comment]
Fixed on master
