### ISSUE TITLE
JBehave Support plugin crashing in IntelliJ Idea ultimate 2016.3.5

### ISSUE THREAD

**Issue by quantumcheese** [witspirit/IntelliJBehave#42]
Almost every time I open a .feature file (associated as a JBehave Story file type), I get exceptions in my "IDE Fatal Errors" log:

```
Worker exited due to exception
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.jbehave.core.steps.PatternVariantBuilder.variantsFor(PatternVariantBuilder.java:140)
	at org.jbehave.core.steps.PatternVariantBuilder.<init>(PatternVariantBuilder.java:117)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:58)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:55)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:314)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
	at com.google.common.collect.FluentIterable.toSet(FluentIterable.java:396)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:181)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
	at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.multiResolve(StepPsiReference.java:119)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:56)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:623)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:522)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:504)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:105)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:836)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:776)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:821)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:70)
	at com.intellij.openapi.progress.util.ReadTask$1.compute(ReadTask.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:67)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:199)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:196)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:219)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:44)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.jbehave.core.steps.PatternVariantBuilder.variantsFor(PatternVariantBuilder.java:140)
	at org.jbehave.core.steps.PatternVariantBuilder.<init>(PatternVariantBuilder.java:117)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:58)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:55)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:314)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
	at com.google.common.collect.FluentIterable.toSet(FluentIterable.java:396)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:181)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
	at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.multiResolve(StepPsiReference.java:119)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:56)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:391)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:368)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:238)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:210)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:312)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.jbehave.core.steps.PatternVariantBuilder.variantsFor(PatternVariantBuilder.java:140)
	at org.jbehave.core.steps.PatternVariantBuilder.<init>(PatternVariantBuilder.java:117)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:58)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:55)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:314)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
	at com.google.common.collect.FluentIterable.toSet(FluentIterable.java:396)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:181)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
	at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinitions(StepPsiReference.java:109)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolveToDefinition(StepPsiReference.java:102)
	at com.github.kumaraman21.intellijbehave.resolver.StoryAnnotator.annotate(StoryAnnotator.java:45)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.jbehave.core.steps.PatternVariantBuilder.variantsFor(PatternVariantBuilder.java:140)
	at org.jbehave.core.steps.PatternVariantBuilder.<init>(PatternVariantBuilder.java:117)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:58)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil$5.apply(JBehaveUtil.java:55)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:314)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
	at com.google.common.collect.FluentIterable.toSet(FluentIterable.java:396)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAliasesAnnotationTexts(JBehaveUtil.java:181)
	at com.github.kumaraman21.intellijbehave.service.JBehaveUtil.getAnnotationTexts(JBehaveUtil.java:142)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getAnnotationTexts(JavaStepDefinition.java:103)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.getStepMatchers(JavaStepDefinition.java:76)
	at com.github.kumaraman21.intellijbehave.service.JavaStepDefinition.matches(JavaStepDefinition.java:36)
	at com.github.kumaraman21.intellijbehave.service.JBehaveStepsIndex.findStepDefinitions(JBehaveStepsIndex.java:44)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.multiResolve(StepPsiReference.java:119)
	at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:56)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
	at com.intellij.codeInsight.intention.impl.AddAnnotationIntention.isAvailable(AddAnnotationIntention.java:50)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:59)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)



```

**Comment by quantumcheese** [comment]
Seems like 
`https://github.com/witspirit/IntelliJBehave/blob/master/src/com/github/kumaraman21/intellijbehave/service/JBehaveUtil.java line 57
`     public Set<String> apply(@Nullable String value) {`
Should not be @nullable.  I can submit a PR, but I don't know how to build and test IDEA plugins.

**Comment by quantumcheese** [comment]
Please see PR #43 https://github.com/witspirit/IntelliJBehave/pull/43.

**Comment by JenoDK** [comment]
Fixed on master
