### ISSUE TITLE
Incompatible with 2021.1.3

### ISSUE THREAD

**Issue by KristianAtVsp** [witspirit/IntelliJBehave#58]
![image](https://user-images.githubusercontent.com/45828766/124969200-46960200-dfdb-11eb-9fdc-cd0c1c308762.png)
It still works fine on my old machine where I have the plugin installed, but is unable to install on my new machine because it is "marked as incompatible" I see in your build.gradle file you have "jbehave.updateSinceUntilBuild false" which should work, but apparently is not working properly.

**Comment by mikeloguay** [comment]
Same for me in 2021.2 Ultimate Edition on Windows. This error appears after open the IDE:

`java.lang.ClassNotFoundException: com.github.kumaraman21.intellijbehave.template.JBehaveTemplateLoaderComponent
             PluginClassLoader(plugin=PluginDescriptor(name=JBehave Support, id=jbehave-support-plugin, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.2\plugins\JBehave Support, version=1.53, package=null), packagePrefix=null, instanceId=55, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:89)
    at com.intellij.ide.a.m.f.a(f.java:93)
    at com.intellij.ide.a.m.bM.a(bM.java:310)
    at com.intellij.ide.a.m.bT.a(bT.java:278)
    at com.intellij.ide.a.m.bT.c(bT.java:171)
    at com.intellij.ide.a.m.bT.b(bT.java:81)
    at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by picimako** [comment]
To make things simpler, discussion on upgrade related issues will be continued on #60.
