### ISSUE TITLE
how to build plugin from sources and install it to Idea by jar 

### ISSUE THREAD

**Issue by roman-finix** [witspirit/IntelliJBehave#74]
I do not know why , but I can not download any version from https://plugins.jetbrains.com/plugin/7268-jbehave-support/versions 

there is always error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
```

I try to [build plugin](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#buildplugin-task) from sources:
```
  $ git clone git@github.com:witspirit/IntelliJBehave.git
  $ cd IntelliJBehave/
  $ ./gradlew buildPlugin
  $ find . -name *.jar | more
  ...
  ./build/idea-sandbox/plugins/JBehave Support/lib/gson-2.8.5.jar
./build/idea-sandbox/plugins/JBehave Support/lib/IntelliJBehave.jar
./build/idea-sandbox/plugins/JBehave Support/lib/commons-io-2.8.0.jar
./build/idea-sandbox/plugins/JBehave Support/lib/xstream-1.4.15.jar
./build/idea-sandbox/plugins/JBehave Support/lib/freemarker-2.3.30.jar
./build/idea-sandbox/plugins/JBehave Support/lib/plexus-utils-3.3.0.jar
./build/idea-sandbox/plugins/JBehave Support/lib/commons-text-1.9.jar
./build/idea-sandbox/plugins/JBehave Support/lib/junit-4.13.1.jar
./build/idea-sandbox/plugins/JBehave Support/lib/annotations-13.0.jar
./build/idea-sandbox/plugins/JBehave Support/lib/jbehave-core-4.8.3.jar
./build/idea-sandbox/plugins/JBehave Support/lib/paranamer-2.8.jar
./build/idea-sandbox/plugins/JBehave Support/lib/kotlin-stdlib-common-1.4.32.jar
./build/idea-sandbox/plugins/JBehave Support/lib/hamcrest-core-1.3.jar
./build/idea-sandbox/plugins/JBehave Support/lib/kotlin-stdlib-1.4.32.jar
./build/idea-sandbox/plugins/JBehave Support/lib/xmlpull-1.1.3.1.jar
./build/idea-sandbox/plugins/JBehave Support/lib/xpp3_min-1.1.4c.jar
./build/idea-sandbox/plugins/JBehave Support/lib/hamcrest-2.2.jar
./build/idea-sandbox/plugins/JBehave Support/lib/commons-lang3-3.11.jar
```

I do install from disk in IDEA for `IntelliJBehave.jar`
but it fails with Error class not found
```
java.lang.NoClassDefFoundError: org/jbehave/core/configuration/Keywords
	at com.github.kumaraman21.intellijbehave.highlighter.StoryLexerFactory.createLexer(StoryLexerFactory.java:13)
	at com.github.kumaraman21.intellijbehave.highlighter.StorySyntaxHighlightingLexer.<init>(StorySyntaxHighlightingLexer.java:22)
	at com.github.kumaraman21.intellijbehave.highlighter.StorySyntaxHighlighter.getHighlightingLexer(StorySyntaxHighlighter.java:40)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.<init>(LexerEditorHighlighter.java:58)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:28)
	at com.intellij.openapi.fileTypes.FileTypeEditorHighlighterProviders$1.getEditorHighlighter(FileTypeEditorHighlighterProviders.java:40)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:66)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:83)
	at com.intellij.openapi.fileEditor.impl.text.EditorHighlighterUpdater.createHighlighter(EditorHighlighterUpdater.java:137)
	at com.intellij.openapi.fileEditor.impl.text.EditorHighlighterUpdater.lambda$updateHighlightersAsync$0(EditorHighlighterUpdater.java:126)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.jbehave.core.configuration.Keywords PluginClassLoader(plugin=PluginDescriptor(name=JBehave Support, id=jbehave-support-plugin, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.1/plugins/IntelliJBehave.jar, version=1.57, package=null, isBundled=false), packagePrefix=null, instanceId=323, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 40 more
``` 

How to build and install it ?

**Comment by roman-finix** [comment]
solution is
```
$ find . -name *.zip
./build/distributions/JBehave Support.zip
```

and use zip to load/install from Disk.
